import type { TheoryBlock } from "@/types/theory-block";

export const MOCK_THEORY_BLOCKS: TheoryBlock[] = [
  {
    id: "tb-1",
    title: "Sleep extension for cognitive performance",
    goalCategory: "Cognitive",
    goalStatement: "Improve focus and reaction time by extending sleep to 7.5–8h.",
    evidenceTier: "Strong",
    riskLevel: "Low",
    reversibility: "High",
    mechanismSummary: "Sleep consolidates memory and clears metabolic waste; adequate duration improves prefrontal function.",
    interventions: [
      {
        tier: "Strong",
        name: "Fixed wake time + wind-down",
        mechanism: "Stabilize circadian phase and reduce sleep latency.",
        steps: ["Set alarm 7.5h after target bedtime", "No screens 1h before bed", "Dim lights 2h before"],
        durationDays: 14,
        trackingMetrics: ["Sleep duration", "Sleep onset latency", "Subjective alertness"],
        expectedMagnitude: "Medium",
        riskLevel: "Low",
        reversibility: "High",
        contraindications: [],
      },
    ],
    tags: ["sleep", "cognition", "performance"],
    traction: { saves: 124, experimentLogs: 89, avgOutcome: 7.2 },
  },
  {
    id: "tb-2",
    title: "Morning light for mood and energy",
    goalCategory: "Mood",
    goalStatement: "Reduce low mood and increase morning energy with 20min outdoor light.",
    evidenceTier: "Strong",
    riskLevel: "Low",
    reversibility: "High",
    mechanismSummary: "Bright light suppresses melatonin and phase-advances circadian rhythm; supports serotonin and alertness.",
    interventions: [
      {
        tier: "Strong",
        name: "Morning light exposure",
        mechanism: "Phase advance and melatonin suppression.",
        steps: ["Within 1h of wake, get 20min outdoors or 10k lux lamp", "Avoid bright light late evening"],
        durationDays: 7,
        trackingMetrics: ["Mood 1–10", "Energy 1–10", "Sleep quality"],
        expectedMagnitude: "Medium",
        riskLevel: "Low",
        reversibility: "High",
        contraindications: ["Bipolar disorder", "Photosensitivity"],
      },
    ],
    tags: ["light", "mood", "circadian"],
    traction: { saves: 98, experimentLogs: 67, avgOutcome: 6.8 },
  },
  {
    id: "tb-3",
    title: "Zone 2 cardio for metabolic health",
    goalCategory: "Metabolic",
    goalStatement: "Improve insulin sensitivity and fat oxidation with 3×30min zone 2 per week.",
    evidenceTier: "Strong",
    riskLevel: "Low",
    reversibility: "High",
    mechanismSummary: "Low-intensity aerobic work increases mitochondrial density and fatty acid oxidation; improves insulin signaling.",
    interventions: [
      {
        tier: "Strong",
        name: "Zone 2 protocol",
        mechanism: "Mitochondrial adaptation and metabolic flexibility.",
        steps: ["Warm up 5min", "30min at ~60–70% max HR or conversational pace", "Cool down 5min"],
        durationDays: 84,
        trackingMetrics: ["Fasting glucose", "Resting HR", "RPE"],
        expectedMagnitude: "Medium",
        riskLevel: "Low",
        reversibility: "High",
        contraindications: ["Unstable cardiovascular disease"],
      },
    ],
    tags: ["cardio", "metabolic", "zone2"],
    traction: { saves: 156, experimentLogs: 112, avgOutcome: 7.5 },
  },
  {
    id: "tb-4",
    title: "Resistance training for strength",
    goalCategory: "Physical",
    goalStatement: "Increase strength and lean mass with 2× full-body resistance per week.",
    evidenceTier: "Strong",
    riskLevel: "Moderate",
    reversibility: "Medium",
    mechanismSummary: "Progressive overload and recovery drive hypertrophy and neuromuscular adaptation.",
    interventions: [
      {
        tier: "Strong",
        name: "Full-body strength",
        mechanism: "Mechanical tension and metabolic stress.",
        steps: ["Compound lifts 3×8–12", "Progressive overload weekly", "48h between sessions"],
        durationDays: 56,
        trackingMetrics: ["Lift loads", "Body weight", "Soreness"],
        expectedMagnitude: "Medium",
        riskLevel: "Moderate",
        reversibility: "Medium",
        contraindications: ["Acute injury", "Uncontrolled hypertension"],
      },
    ],
    tags: ["strength", "hypertrophy", "resistance"],
    traction: { saves: 203, experimentLogs: 145, avgOutcome: 7.1 },
  },
  {
    id: "tb-5",
    title: "Cold exposure for resilience",
    goalCategory: "Recovery",
    goalStatement: "Improve stress resilience and recovery with short cold exposure.",
    evidenceTier: "Emerging",
    riskLevel: "Moderate",
    reversibility: "High",
    mechanismSummary: "Cold activates sympathetic and norepinephrine response; may support mood and recovery signaling.",
    interventions: [
      {
        tier: "Emerging",
        name: "Cold shower / immersion",
        mechanism: "Sympathetic activation and possible anti-inflammatory effects.",
        steps: ["End shower with 1–3min cold", "Or 2–5min immersion to shoulders"],
        durationDays: 14,
        trackingMetrics: ["HRV", "Mood", "Perceived recovery"],
        expectedMagnitude: "Small",
        riskLevel: "Moderate",
        reversibility: "High",
        contraindications: ["Cardiovascular disease", "Raynaud's", "Pregnancy"],
      },
    ],
    tags: ["cold", "recovery", "stress"],
    traction: { saves: 87, experimentLogs: 54, avgOutcome: 5.9 },
  },
  {
    id: "tb-6",
    title: "Intermittent fasting for body composition",
    goalCategory: "Metabolic",
    goalStatement: "Support fat loss and metabolic flexibility with 16:8 fasting.",
    evidenceTier: "Emerging",
    riskLevel: "Low",
    reversibility: "High",
    mechanismSummary: "Extended fasting window may enhance fat oxidation and autophagy; evidence mixed for superior fat loss vs. calorie match.",
    interventions: [
      {
        tier: "Emerging",
        name: "16:8 daily fasting",
        mechanism: "Extended low-insulin window and possible autophagy.",
        steps: ["Eat within 8h window", "Hydrate in fast", "Prioritize protein in eating window"],
        durationDays: 28,
        trackingMetrics: ["Weight", "Energy", "Hunger"],
        expectedMagnitude: "Small",
        riskLevel: "Low",
        reversibility: "High",
        contraindications: ["Eating disorders", "Diabetes on meds", "Pregnancy"],
      },
    ],
    tags: ["fasting", "metabolic", "body-composition"],
    traction: { saves: 134, experimentLogs: 78, avgOutcome: 6.2 },
  },
  {
    id: "tb-7",
    title: "Nootropic stack for focus",
    goalCategory: "Cognitive",
    goalStatement: "Enhance sustained focus with caffeine + L-theanine.",
    evidenceTier: "Emerging",
    riskLevel: "Low",
    reversibility: "High",
    mechanismSummary: "Caffeine antagonizes adenosine; L-theanine may smooth stimulation and reduce jitter.",
    interventions: [
      {
        tier: "Emerging",
        name: "Caffeine + L-theanine",
        mechanism: "Adenosine antagonism with modulated arousal.",
        steps: ["~100mg caffeine + 200mg L-theanine", "Take in morning or before deep work"],
        durationDays: 7,
        trackingMetrics: ["Focus self-report", "HR", "Sleep that night"],
        expectedMagnitude: "Small",
        riskLevel: "Low",
        reversibility: "High",
        contraindications: ["Anxiety disorders", "Heart conditions", "Pregnancy"],
      },
    ],
    tags: ["nootropics", "focus", "cognition"],
    traction: { saves: 76, experimentLogs: 43, avgOutcome: 5.5 },
  },
  {
    id: "tb-8",
    title: "Sauna for cardiovascular and mood",
    goalCategory: "Recovery",
    goalStatement: "Support cardiovascular and mood with 2×20min sauna per week.",
    evidenceTier: "Theoretical",
    riskLevel: "Moderate",
    reversibility: "High",
    mechanismSummary: "Heat stress may induce heat-shock proteins and improve endothelial function; observational links to cardiovascular and mood.",
    interventions: [
      {
        tier: "Theoretical",
        name: "Sauna protocol",
        mechanism: "Heat shock response and possible endothelial adaptation.",
        steps: ["2×20min at 80–90°C", "Cool down between rounds", "Hydrate well"],
        durationDays: 56,
        trackingMetrics: ["Resting HR", "Mood", "Recovery"],
        expectedMagnitude: "Small",
        riskLevel: "Moderate",
        reversibility: "High",
        contraindications: ["Unstable cardiovascular", "Pregnancy", "Certain medications"],
      },
    ],
    tags: ["sauna", "recovery", "cardiovascular"],
    traction: { saves: 62, experimentLogs: 31, avgOutcome: 5.2 },
  },
];

export const MOCK_SAVED_IDS: string[] = ["tb-1", "tb-3", "tb-5"];

export function getTheoryBlockById(id: string): TheoryBlock | undefined {
  return MOCK_THEORY_BLOCKS.find((b) => b.id === id);
}

export function getSavedTheoryBlocks(): TheoryBlock[] {
  return MOCK_SAVED_IDS.map((id) => getTheoryBlockById(id)).filter(
    (b): b is TheoryBlock => b !== undefined
  );
}
